apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploymentName }}
  namespace: {{ .Values.namespace }}
  labels:
    product: TestApplication
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      release: {{ .Values.deploymentName }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        release: {{ .Values.deploymentName }}
        product: TestApplication
    spec:
      imagePullSecrets:
        - name: {{ .Values.imageSecret }}
      hostname: {{ .Values.deploymentName }}
      containers:
        - name: {{ .Values.deploymentName }}
          image: {{ .Values.imageName }}
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5
          ports:
            - containerPort: 8080
          env:
            - name: PROFILE
              value: {{ .Values.env }}
            - name: FILE_PATH
              value: /usr/share/html/index.html
          volumeMounts:
            - name: mnt
              mountPath: /usr/share/html/index.html
              subPath: file-from-cfgmap
      volumes:
        - name: mnt
          configMap:
            name: nginx-cfgmap
